openapi: 3.1.0

info:
  title: Grocy API (Enriched via Cloudflare Worker)
  version: "1.2.2"
  description: >
    GPT-oriented Grocy API exposed via a Cloudflare Worker.
    Native Grocy endpoints are proxied with strict limits.
    Enriched endpoints provide denormalized, human-readable responses
    with fuzzy resolution and partial-success semantics.

    Clients should treat ambiguity responses as terminal and
    request user clarification before retrying.

    IMPORTANT BEHAVIOUR NOTES:
    - Product name resolution is fuzzy and may be ambiguous.
    - Bulk operations may partially succeed.
    - Quantity units and pricing are informational only.
    - Hard limits are enforced silently by the server.

  x-capabilities:
    fuzzy_product_resolution: true
    partial_success_bulk_operations: true
    implicit_unit_handling: true
    silent_truncation: true
    denormalized_responses: true

servers:
  - url: https://grocy-butler.joshscomputer.com

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:

    # -----------------------------
    # Error schemas
    # -----------------------------
    ProductNotFound:
      type: object
      properties:
        error:
          type: string
          enum: [product_not_found]
        product:
          type: string
      required: [error, product]

    MultipleProducts:
      type: object
      properties:
        error:
          type: string
          enum: [multiple_products]
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required: [id, name]
      required: [error, products]

    MultipleShoppingLists:
      type: object
      properties:
        error:
          type: string
          enum: [multiple_lists]
        lists:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required: [id, name]
      required: [error, lists]

    # -----------------------------
    # Stock
    # -----------------------------
    EnrichedStockItem:
      type: object
      properties:
        stock_id:
          type: integer
        product_id:
          type: integer
        product_name:
          type: string
        amount:
          type: number
        best_before_date:
          type: string
          format: date
          nullable: true
      required: [stock_id, product_id, product_name, amount]

    # -----------------------------
    # Shopping list
    # -----------------------------
    EnrichedShoppingList:
      type: object
      properties:
        list:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
          required: [id, name]
        items:
          type: array
          items:
            $ref: "#/components/schemas/EnrichedShoppingListItem"
      required: [list, items]

    EnrichedShoppingListItem:
      type: object
      properties:
        product_id:
          type: integer
        product_name:
          type: string
        amount:
          type: number
        note:
          type: string
          nullable: true
        last_store:
          type: string
          nullable: true
        pricing:
          type: object
          description: >
            Pricing context derived from the last recorded purchase.
            Values are informational only and may include unit identifiers
            and conversion factors. Do not assume arithmetic correctness
            unless explicitly instructed.
          additionalProperties: true
      required: [product_id, product_name, amount]

    # -----------------------------
    # Product search
    # -----------------------------
    EnrichedProductSearchResult:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        confidence:
          type: number
          minimum: 0
          maximum: 1
      required: [id, name, confidence]

    EnrichedProductSearchResponse:
      type: object
      properties:
        query:
          type: string
        matches:
          type: array
          maxItems: 10
          items:
            $ref: "#/components/schemas/EnrichedProductSearchResult"
      required: [query, matches]

responses:

  EnrichedStockResponse:
    description: Enriched inventory retrieved
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: "#/components/schemas/EnrichedStockItem"

  ProductResolutionError:
    description: Product resolution failed
    content:
      application/json:
        schema:
          oneOf:
            - $ref: "#/components/schemas/ProductNotFound"
            - $ref: "#/components/schemas/MultipleProducts"

paths:

  # =============================
  # Stock
  # =============================
  /api/enriched/stock:
    get:
      summary: Get inventory (enriched)
      description: >
        Returns a truncated, enriched view of current stock.
        The server enforces a hard item limit and may silently truncate results.
      operationId: getStock
      responses:
        "200":
          description: Enriched inventory retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnrichedStockItem"
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  /api/enriched/stock/add:
    post:
      summary: Add inventory (enriched)
      x-stop-on-ambiguity: true
      description: >
        Adds inventory using a fuzzy product name match.
        If multiple products match, the client must stop
        and request clarification from the user.

        Fields such as unit and store are accepted for compatibility
        but are currently ignored by the system.
      operationId: addStock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: string
                amount:
                  type: number
                unit:
                  type: string
                  description: Accepted for compatibility only. Currently ignored.
                price:
                  type: number
                store:
                  type: string
                  description: Accepted for compatibility only. Currently ignored.
                best_before_date:
                  type: string
                  format: date
              required: [product, amount]
      responses:
        "200":
          description: Inventory added
        "400":
          description: Product resolution failed
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ProductNotFound"
                  - $ref: "#/components/schemas/MultipleProducts"
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  /api/enriched/stock/add/bulk:
    post:
      summary: Add inventory in bulk
      x-stop-on-ambiguity: true
      description: >
        Adds multiple inventory items in a single request.
        Each line is processed independently.
        Partial success is expected and normal.
        Maximum of 25 items are processed per request.
      operationId: addStockBulk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                store:
                  type: string
                purchased_at:
                  type: string
                  format: date
                items:
                  type: array
                  maxItems: 25
                  items:
                    type: object
                    properties:
                      line:
                        type: integer
                      product:
                        type: string
                      amount:
                        type: number
                      best_before_date:
                        type: string
                        format: date
                      price:
                        type: number
                    required: [product, amount]
              required: [items]
      responses:
        "200":
          $ref: "#/components/responses/EnrichedStockResponse"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [completed]
                  summary:
                    type: object
                    properties:
                      total:
                        type: integer
                      added:
                        type: integer
                      errors:
                        type: integer
                  results:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                required: [status, summary, results]
              examples:
                mixed_result:
                  summary: Some items added, some failed
                  value:
                    status: completed
                    summary:
                      total: 3
                      added: 2
                      errors: 1
                    results:
                      - line: 1
                        status: added
                        product:
                          id: 12
                          name: Milk
                      - line: 2
                        status: error
                        error: multiple_products
                        candidates:
                          - id: 8
                            name: Cream
                          - id: 9
                            name: Cooking Cream
                      - line: 3
                        status: added
                        product:
                          id: 5
                          name: Bread
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  # =============================
  # Shopping list
  # =============================
  /api/enriched/shopping_list:
    get:
      summary: Get shopping list (enriched)
      operationId: getShoppingList
      parameters:
        - name: list_id
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: Shopping list retrieved
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/EnrichedShoppingList"
                  - $ref: "#/components/schemas/MultipleShoppingLists"
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  /api/enriched/shopping_list/add:
    post:
      summary: Add item to shopping list (enriched)
      x-stop-on-ambiguity: true
      operationId: addToShoppingList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: string
                amount:
                  type: number
                note:
                  type: string
                shopping_list_id:
                  type: integer
              required: [product, amount]
      responses:
        "200":
          description: Item added
        "400":
          description: Product resolution failed
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ProductNotFound"
                  - $ref: "#/components/schemas/MultipleProducts"
                  - $ref: "#/components/schemas/MultipleShoppingLists"
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  # =============================
  # Products
  # =============================
  /api/enriched/products/search:
    get:
      summary: Search products (enriched)
      operationId: searchProducts
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 5
            minimum: 1
            maximum: 10
      responses:
        "200":
          description: Product search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnrichedProductSearchResponse"
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  /api/enriched/products/create:
    post:
      summary: Create product (enriched)
      description: >
        Creates a new product using human-readable fields.
        Mandatory fields are resolved automatically.
        Duplicate product names are rejected.
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                default_location:
                  type: string
                quantity_units:
                  type: object
                product_group:
                  type: string
                image_url:
                  type: string
                  format: uri
              required: [name]
      responses:
        "200":
          description: Product created
        "400":
          description: Invalid request or duplicate product
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error
