openapi: 3.1.0

info:
  title: Grocy API (Limited + Enriched via Cloudflare Worker)
  description: >
    Limited Grocy access via a Cloudflare Worker.
    Native Grocy object endpoints are proxied as-is.
    Enriched endpoints provide GPT-safe, denormalized views.
  version: "1.2.0"

servers:
  - url: https://grocy-butler.joshscomputer.com

components:
  schemas:
    EnrichedStockItem:
      type: object
      properties:
        stock_id:
          type: integer
        product_id:
          type: integer
        product_name:
          type: string
        amount:
          type: number
        best_before_date:
          type: string
          format: date
      required: [stock_id, product_id, product_name, amount]

    EnrichedShoppingList:
      type: object
      properties:
        list:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
          required: [id, name]
        items:
          type: array
          items:
            $ref: "#/components/schemas/EnrichedShoppingListItem"
      required: [list, items]

    EnrichedShoppingListItem:
      type: object
      properties:
        product_id:
          type: integer
        product_name:
          type: string
        amount:
          type: number
        note:
          type: string
      required: [product_id, product_name, amount]

    MultipleShoppingLists:
      type: object
      properties:
        error:
          type: string
          enum: [multiple_lists]
        lists:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required: [id, name]
      required: [error, lists]

    ProductNotFound:
      type: object
      properties:
        error:
          type: string
          enum: [product_not_found]
        product:
          type: string
      required: [error, product]

    MultipleProducts:
      type: object
      properties:
        error:
          type: string
          enum: [multiple_products]
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required: [id, name]
      required: [error, products]

    EnrichedProductSearchResult:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        confidence:
          type: number
          minimum: 0
          maximum: 1
      required: [id, name, confidence]

    EnrichedProductSearchResponse:
      type: object
      properties:
        query:
          type: string
        matches:
          type: array
          items:
            $ref: "#/components/schemas/EnrichedProductSearchResult"
      required: [query, matches]

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []

paths:
  /api/enriched/stock/add/bulk:
    post:
      summary: Add inventory in bulk (receipt-driven, enriched)
      description: >
        Adds multiple inventory items in a single request.
        Intended for receipt-based workflows driven by GPT.
        Each item is processed independently; partial success is allowed.
      operationId: addStockBulk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                store:
                  type: string
                  description: Optional store name
                purchased_at:
                  type: string
                  format: date
                items:
                  type: array
                  maxItems: 25
                  items:
                    type: object
                    properties:
                      line:
                        type: integer
                        description: Receipt line number
                      product:
                        type: string
                        description: Product name from receipt
                      amount:
                        type: number
                      best_before_date:
                        type: string
                        format: date
                      price:
                        type: number
                    required:
                      - product
                      - amount
              required:
                - items
      responses:
        "200":
          description: Bulk inventory processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [completed]
                  summary:
                    type: object
                    properties:
                      total:
                        type: integer
                      added:
                        type: integer
                      errors:
                        type: integer
                  results:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                required:
                  - status
                  - summary
                  - results
        "400":  
          description: Invalid request
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  /api/enriched/products/create:
    post:
      summary: Create a new product (enriched)
      description: >
        Creates a new product using human-readable fields.
        Resolves mandatory location and quantity units.
        Optionally attaches a product image via URL.
        Performs de-duplication and cache-safe writes.
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product name (must be unique)
                description:
                  type: string
                default_location:
                  type: string
                  description: Human-readable location name
                quantity_units:
                  type: object
                  properties:
                    stock:
                      type: string
                    purchase:
                      type: string
                    consume:
                      type: string
                    price:
                      type: string
                  description: Human-readable quantity unit names
                product_group:
                  type: string
                image_url:
                  type: string
                  format: uri
                  description: The URL must be directly fetchable from a server environment. Some image hosts block server-side requests.
              required: [name]
      responses:
        "200":
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [created]
                  product:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                    required: [id, name]
                  image:
                    type: object
                    properties:
                      attached:
                        type: boolean
                    required: [attached]
                required: [status, product]
        "400":
          description: Invalid request or duplicate product
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error

  /api/enriched/stock:
    get:
      summary: Get inventory
      operationId: getStock
      responses:
        "200":
          description: Enriched inventory retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnrichedStockItem"

  /api/enriched/shopping_list:
    get:
      summary: Get shopping list (enriched)
      operationId: getShoppingList
      parameters:
        - name: list_id
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: Shopping list retrieved
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/EnrichedShoppingList"
                  - $ref: "#/components/schemas/MultipleShoppingLists"

  /api/enriched/products/search:
    get:
      summary: Search products (enriched)
      operationId: searchProducts
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 5
            minimum: 1
            maximum: 10
      responses:
        "200":
          description: Product search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnrichedProductSearchResponse"

  /api/enriched/shopping_list/add:
    post:
      summary: Add item to shopping list (enriched)
      operationId: addToShoppingList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: string
                amount:
                  type: number
                note:
                  type: string
                shopping_list_id:
                  type: integer
              required: [product, amount]

  /api/enriched/stock/add:
    post:
      summary: Add inventory (enriched, receipt-friendly)
      description: >
        Adds inventory using a human-readable product name.
        Intended for receipt-based workflows driven by GPT.
        Resolves products fuzzily and applies Grocy-safe defaults.
      operationId: addStock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: string
                  description: Product name from receipt
                amount:
                  type: number
                  description: Quantity purchased
                unit:
                  type: string
                  description: Optional receipt unit (e.g. bottle, pack)
                price:
                  type: number
                  description: Optional total or unit price
                store:
                  type: string
                  description: Optional store name
                best_before_date:
                  type: string
                  format: date
              required:
                - product
                - amount
      responses:
        "200":
          description: Inventory added
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [added]
                  product:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                    required: [id, name]
                  interpreted_as:
                    type: object
                    additionalProperties: true
                required:
                  - status
                  - product
        "400":
          description: Invalid request or ambiguous product
        "401":
          description: Unauthorized
        "502":
          description: Upstream Grocy error
